In [1]:
import numpy as np

In [3]:
np_array = np.array([1,2,3])
print(np_array *5 )

[ 5 10 15]


In [4]:
# zero array 
zero= np.zeros(5)
print(zero)

[0. 0. 0. 0. 0.]


In [5]:
x= input()
print(type(x))


<class 'str'>


In [6]:
# two dimensional array with zeros
np.zeros((2,2))


array([[0., 0.],
       [0., 0.]])

In [8]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:

np.linspace(2, 20, 5)

array([ 2. ,  6.5, 11. , 15.5, 20. ])

In [11]:
# identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [14]:
a= np.array([[1,2,3],
            [4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
print(f"Data type (dtype):       {a.dtype}")
print(f"Shape (rows, cols):     {a.shape}")
print(f"Total elements (size):  {a.size}")
print(f"Number of dimensions:   {a.ndim}")
print(f"Bytes per item:         {a.itemsize} bytes")
print(f"Total memory (nbytes):  {a.nbytes} bytes")

Data type (dtype):       int64
Shape (rows, cols):     (2, 3)
Total elements (size):  6
Number of dimensions:   2
Bytes per item:         8 bytes
Total memory (nbytes):  48 bytes


In [17]:
arr= np.arange(9)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [18]:
arr.shape

(9,)

In [19]:
arr.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [20]:
import random

In [23]:
np.random.seed(1337)
np.random.randint(1,10)

8