In [1]:
import numpy as np

In [3]:
np_array = np.array([1,2,3])
print(np_array *5 )

[ 5 10 15]


In [4]:
# zero array 
zero= np.zeros(5)
print(zero)

[0. 0. 0. 0. 0.]


In [5]:
x= input()
print(type(x))


<class 'str'>


In [6]:
# two dimensional array with zeros
np.zeros((2,2))


array([[0., 0.],
       [0., 0.]])

In [8]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:

np.linspace(2, 20, 5)

array([ 2. ,  6.5, 11. , 15.5, 20. ])

In [11]:
# identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [14]:
a= np.array([[1,2,3],
            [4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
print(f"Data type (dtype):       {a.dtype}")
print(f"Shape (rows, cols):     {a.shape}")
print(f"Total elements (size):  {a.size}")
print(f"Number of dimensions:   {a.ndim}")
print(f"Bytes per item:         {a.itemsize} bytes")
print(f"Total memory (nbytes):  {a.nbytes} bytes")

Data type (dtype):       int64
Shape (rows, cols):     (2, 3)
Total elements (size):  6
Number of dimensions:   2
Bytes per item:         8 bytes
Total memory (nbytes):  48 bytes


In [17]:
arr= np.arange(9)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [18]:
arr.shape

(9,)

In [19]:
arr.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [20]:
import random

In [23]:
np.random.seed(1337)
np.random.randint(1,10)

8

## More NumPy Basics


In [ ]:
# basic indexing and slicing
matrix = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
print(matrix[0])
print(matrix[1, 2])
print(matrix[:, 1])
print(matrix[0:2, 1:3])

In [ ]:
# array math and broadcasting
prices = np.array([100, 200, 300])
tax = prices * 0.05
total = prices + tax
print(prices)
print(tax)
print(total)

In [ ]:
# reshape a 1D array into 2D
numbers = np.arange(1, 13)
reshaped = numbers.reshape(3, 4)
print(numbers)
print(reshaped)

In [ ]:
# transpose and flatten
grid = np.array([[1, 2, 3], [4, 5, 6]])
print(grid.T)
print(grid.flatten())

In [ ]:
# random arrays
np.random.seed(7)
rand_array = np.random.randint(1, 100, size=(3, 3))
print(rand_array)
print(rand_array.min())
print(rand_array.max())

In [ ]:
scores = np.array([45, 72, 88, 59, 91])
passed = scores[scores >= 60]
print(scores)
print(passed)

In [ ]:
left = np.array([1, 2, 3])
right = np.array([4, 5, 6])
print(np.concatenate([left, right]))
print(np.vstack([left, right]))
print(np.hstack([left, right]))

In [ ]:
practice = np.arange(1, 6)
squared = practice ** 2
print(practice)
print(squared)
print(practice.mean())

In [ ]:
# array statistics
data = np.array([12, 15, 18, 21, 24])
print(data.sum())
print(data.mean())
print(data.min())
print(data.max())
print(data.std())

In [24]:
# copy versus view
ori = np.array([1, 2, 3])
view = ori
copy = ori.copy()
view[0] = 99
copy[1] = 77
print(ori)
print(view)
print(copy)

[99  2  3]
[99  2  3]
[ 1 77  3]
